import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import { readTrackingPlan } from '../lib/utils/tracking-plan';
import type { TrackingPlan, TrackingPlanEvent, EventProperty } from '../lib/types';

type ExportFormat = 'segment' | 'amplitude' | 'opentelemetry' | 'glassflow';

export async function exportCommand(options: {
  cwd?: string;
  format?: ExportFormat;
  output?: string;
}): Promise<void> {
  const cwd = options.cwd ?? process.cwd();
  const format = options.format ?? 'segment';

  const plan = readTrackingPlan(cwd);
  if (!plan) {
    console.log(chalk.dim('No tracking plan found. Run `logline init && logline spec` first.'));
    return;
  }

  const activeEvents = plan.events.filter((e) => e.status !== 'deprecated');

  let output: string;
  let defaultFilename: string;

  switch (format) {
    case 'segment':
      output = JSON.stringify(buildSegmentPlan(plan, activeEvents), null, 2);
      defaultFilename = 'segment-tracking-plan.json';
      break;
    case 'amplitude':
      output = JSON.stringify(buildAmplitudeTaxonomy(activeEvents), null, 2);
      defaultFilename = 'amplitude-taxonomy.json';
      break;
    case 'opentelemetry':
      output = buildOtelConventions(activeEvents);
      defaultFilename = 'otel-conventions.yaml';
      break;
    case 'glassflow':
      output = JSON.stringify(buildGlassflowConfig(plan, activeEvents), null, 2);
      defaultFilename = 'glassflow-config.json';
      break;
    default:
      console.error(chalk.red(`Unknown format: ${format}. Use: segment, amplitude, opentelemetry, glassflow`));
      process.exit(1);
  }

  const outPath = options.output ?? path.join(cwd, defaultFilename);
  fs.writeFileSync(outPath, output);
  console.log(chalk.bold(`✓ Exported ${format} plan → ${path.relative(cwd, outPath)} (${activeEvents.length} events)`));
}

// ─── Segment Protocols ───

function buildSegmentPlan(plan: TrackingPlan, events: TrackingPlanEvent[]): object {
  return {
    display_name: plan.product?.mission ?? 'Tracking Plan',
    rules: events.map((e) => ({
      name: e.name,
      description: e.description,
      rules: {
        $schema: 'http://json-schema.org/draft-07/schema#',
        type: 'object',
        properties: {
          properties: buildJsonSchema(e.properties ?? []),
        },
      },
    })),
  };
}

function buildJsonSchema(props: EventProperty[]): object {
  const required = props.filter((p) => p.required).map((p) => p.name);
  const properties: Record<string, object> = {};
  for (const p of props) {
    properties[p.name] = {
      description: p.description ?? '',
      type: [segmentType(p.type)],
    };
  }
  return {
    required,
    properties,
  };
}

function segmentType(t: EventProperty['type']): string {
  if (t === 'date') return 'string';
  return t;
}

// ─── Amplitude ───

function buildAmplitudeTaxonomy(events: TrackingPlanEvent[]): object {
  return {
    events: events.map((e) => ({
      name: e.name,
      description: e.description,
      category: e.priority === 'critical' || e.priority === 'high' ? 'core' : 'other',
      properties: (e.properties ?? []).map((p) => ({
        name: p.name,
        description: p.description ?? '',
        type: amplitudeType(p.type),
        is_required: p.required,
      })),
    })),
  };
}

function amplitudeType(t: EventProperty['type']): string {
  if (t === 'date') return 'string';
  if (t === 'object') return 'any';
  return t;
}

// ─── OpenTelemetry Semantic Conventions ───

function buildOtelConventions(events: TrackingPlanEvent[]): string {
  const lines: string[] = [
    '# Generated by Logline — https://github.com/MengyingLi/logline',
    'groups:',
  ];

  for (const e of events) {
    lines.push(`  - id: ${e.name}`);
    lines.push(`    type: event`);
    lines.push(`    brief: "${e.description.replace(/"/g, '\\"')}"`);
    lines.push(`    stability: experimental`);
    if (e.properties?.length) {
      lines.push('    attributes:');
      for (const p of e.properties) {
        lines.push(`      - id: ${p.name}`);
        lines.push(`        type: ${otelType(p.type)}`);
        lines.push(`        requirement_level: ${p.required ? 'required' : 'recommended'}`);
        if (p.description) {
          lines.push(`        brief: "${p.description.replace(/"/g, '\\"')}"`);
        }
      }
    }
  }

  return lines.join('\n') + '\n';
}

function otelType(t: EventProperty['type']): string {
  if (t === 'date') return 'string';
  if (t === 'object') return 'any';
  return t;
}

// ─── GlassFlow ───

function buildGlassflowConfig(plan: TrackingPlan, events: TrackingPlanEvent[]): object {
  return {
    version: '1.0',
    source: {
      name: plan.product?.mission ?? 'Product',
    },
    filters: events.map((e) => ({
      name: `filter_${e.name}`,
      match: { event: e.name },
      action: 'pass',
    })),
    transforms: events
      .filter((e) => e.properties?.some((p) => p.required))
      .map((e) => ({
        name: `validate_${e.name}`,
        match: { event: e.name },
        validate: {
          required: (e.properties ?? []).filter((p) => p.required).map((p) => p.name),
        },
      })),
    schema: {
      events: events.map((e) => ({
        name: e.name,
        properties: (e.properties ?? []).map((p) => ({
          name: p.name,
          type: p.type,
          required: p.required,
        })),
      })),
    },
  };
}
