import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import { readTrackingPlan, writeTrackingPlan, getTrackingPlanPath } from '../lib/utils/tracking-plan';
import { generateMetrics } from '../lib/context/metric-generator';

export async function metricsCommand(options: { cwd?: string; format?: 'json' | 'yaml' }): Promise<void> {
  const cwd = options.cwd ?? process.cwd();
  const plan = readTrackingPlan(cwd);
  if (!plan) {
    console.log(chalk.dim('No tracking plan found. Run `logline init && logline spec` first.'));
    return;
  }

  const metrics = generateMetrics(plan);
  plan.metrics = metrics;
  writeTrackingPlan(cwd, plan);

  if (options.format === 'yaml') {
    const metricsDir = path.join(cwd, 'metrics');
    fs.mkdirSync(metricsDir, { recursive: true });
    for (const m of metrics) {
      const file = path.join(metricsDir, `${m.name}.yml`);
      const yaml = [
        '# Generated by Logline',
        'metric:',
        `  name: ${m.name}`,
        `  label: "${m.description.replace(/"/g, '\\"')}"`,
        '  type: derived',
        `  sql: "${m.formula.replace(/"/g, '\\"')}"`,
        '  timestamp: event_timestamp',
        '  time_grains: [day, week, month]',
        '',
      ].join('\n');
      fs.writeFileSync(file, yaml);
    }
    console.log(chalk.bold(`✓ Wrote ${metrics.length} metrics to metrics/*.yml`));
    return;
  }

  if (options.format === 'json') {
    process.stdout.write(JSON.stringify({ metrics }, null, 2) + '\n');
    return;
  }

  const planPath = getTrackingPlanPath(cwd);
  console.log(chalk.bold(`✓ Metrics written to ${path.relative(cwd, planPath)} (${metrics.length} metrics)`));
}

