import * as fs from 'fs';
import * as path from 'path';
import { execSync, spawnSync } from 'child_process';
import { scanCommand } from './scan';
import type { ScanResult } from './scan';
import { generateTrackingCode } from '../lib/utils/code-generator';
import type { TrackingGap } from '../lib/discovery/tracking-gap-detector';

const IGNORED_EVENTS = [
  'sidebar_interacted',
  'sidebar_toggled',
  'menu_opened',
  'menu_closed',
  'key_pressed',
];

interface PROptions {
  cwd?: string;
  dryRun?: boolean;
  title?: string;
  baseBranch?: string;
}

export async function prCommand(options: PROptions): Promise<void> {
  const cwd = options.cwd ?? process.cwd();
  const baseBranch = options.baseBranch ?? 'main';
  const branchName = `logline/add-analytics-${Date.now()}`;

  console.log('\n🔍 Analyzing codebase for missing analytics...\n');

  // Get scan results
  const scanResult = await scanCommand({ cwd });

  const gaps = scanResult.gaps.filter((g) => !IGNORED_EVENTS.includes(g.suggestedEvent));

  if (gaps.length === 0) {
    console.log('✓ No missing analytics events found!');
    return;
  }

  console.log(`Found ${gaps.length} events to add:\n`);
  for (const gap of gaps) {
    console.log(`  • ${gap.suggestedEvent} → ${gap.location?.file ?? 'unknown'}`);
  }

  if (options.dryRun) {
    console.log('\n📝 Preview of changes:\n');

    for (const gap of gaps) {
      if (!gap.location || gap.location.file === 'unknown') continue;

      const filePath = path.join(cwd, gap.location.file);
      if (!fs.existsSync(filePath)) continue;

      const content = fs.readFileSync(filePath, 'utf-8');
      const lines = content.split('\n');
      const targetLine = getEffectiveTargetLine(content, gap);

      // Generate the tracking code (with context for property mapping, use effective line for param inference)
      const trackingCode = generateTrackingCode(gap, content, targetLine);

      // Show diff preview
      console.log('─'.repeat(60));
      console.log(`📄 ${gap.location.file}:${targetLine}`);
      console.log('─'.repeat(60));

      // Show context (3 lines before)
      const startLine = Math.max(0, targetLine - 4);
      const endLine = Math.min(lines.length, targetLine + 2);

      for (let i = startLine; i < targetLine; i++) {
        console.log(`  ${String(i + 1).padStart(3)} │ ${lines[i]}`);
      }

      // Show insertion (in green)
      const indent = lines[targetLine - 1]?.match(/^(\s*)/)?.[1] || '  ';
      const indentedCode = trackingCode
        .trim()
        .split('\n')
        .map((l) => `\x1b[32m+     │ ${indent}${l}\x1b[0m`)
        .join('\n');
      console.log(indentedCode);

      // Show context (2 lines after)
      for (let i = targetLine; i < endLine; i++) {
        console.log(`  ${String(i + 1).padStart(3)} │ ${lines[i]}`);
      }

      // Show import if needed
      const hasImport =
        /import\s+.*\btrack\b/.test(content) || content.includes("from '@/lib/analytics'");
      if (!hasImport) {
        console.log('\n  \x1b[33mImport to add:\x1b[0m');
        console.log("  \x1b[32m+ import { track } from '@/lib/analytics';\x1b[0m");
      }

      console.log();
    }

    // Check if analytics module needs to be created
    const analyticsPath = path.join(cwd, 'src', 'lib', 'analytics.ts');
    if (!fs.existsSync(analyticsPath)) {
      console.log('─'.repeat(60));
      console.log('📄 src/lib/analytics.ts (new file)');
      console.log('─'.repeat(60));
      console.log('\x1b[32m+ // Analytics module generated by Logline');
      console.log('+ export function track(eventName: string, properties: Record<string, unknown>): void {');
      console.log("+   console.log('[Analytics]', eventName, properties);");
      console.log('+ }\x1b[0m');
      console.log();
    }

    console.log('─'.repeat(60));
    console.log(`\n${gaps.length} events would be added.`);
    console.log('Run `logline pr` without --dry-run to create the PR.\n');
    return;
  }

  // Create branch
  console.log(`\n📦 Creating branch: ${branchName}`);
  execSync(`git checkout -b ${branchName}`, { cwd, stdio: 'inherit' });

  // Group gaps by file so we apply all inserts per file correctly
  const fileToGaps = new Map<string, TrackingGap[]>();
  for (const gap of gaps) {
    if (!gap.location || gap.location.file === 'unknown') continue;
    const filePath = path.join(cwd, gap.location.file);
    if (!fs.existsSync(filePath)) continue;

    const list = fileToGaps.get(gap.location.file) ?? [];
    list.push(gap);
    fileToGaps.set(gap.location.file, list);
  }

  // Apply changes per file (gaps sorted by line descending so inserts don't shift)
  const changedFiles = new Set<string>();

  for (const [relativePath, gaps] of fileToGaps) {
    const filePath = path.join(cwd, relativePath);
    let content = fs.readFileSync(filePath, 'utf-8');

    // Sort by line descending so later inserts don't affect earlier line numbers
    const sorted = [...gaps].sort((a, b) => (b.location?.line ?? 0) - (a.location?.line ?? 0));

    for (const gap of sorted) {
      const targetLine = getEffectiveTargetLine(content, gap);
      const trackingCode = generateTrackingCode(gap, content, targetLine);
      content = insertTracking(content, targetLine, trackingCode);
      content = ensureTrackImport(content, relativePath);
      console.log(`  ✓ ${gap.suggestedEvent} added to ${relativePath}`);
    }

    fs.writeFileSync(filePath, content);
    changedFiles.add(relativePath);
  }

  // Ensure analytics module exists
  ensureAnalyticsModule(cwd);

  // Commit changes
  console.log('\n📝 Committing changes...');
  execSync('git add .', { cwd });
  const commitMsg = `feat(analytics): Add ${gaps.length} tracking events

Events added:
${gaps.map((g) => `- ${g.suggestedEvent}`).join('\n')}

Generated by Logline`;
  const commitFile = path.join(cwd, '.logline', '.commit-msg.txt');
  fs.mkdirSync(path.dirname(commitFile), { recursive: true });
  fs.writeFileSync(commitFile, commitMsg);
  execSync(`git commit -F "${commitFile}"`, { cwd });
  fs.unlinkSync(commitFile);

  // Push and create PR
  console.log('\n🚀 Pushing branch...');
  execSync(`git push -u origin ${branchName}`, { cwd, stdio: 'inherit' });

  // Create PR using GitHub CLI if available
  const prTitle = options.title ?? `feat(analytics): Add ${gaps.length} tracking events`;
  const prBody = generatePRBody({ ...scanResult, gaps });

  try {
    const bodyFile = path.join(cwd, '.logline', '.pr-body.md');
    fs.mkdirSync(path.dirname(bodyFile), { recursive: true });
    fs.writeFileSync(bodyFile, prBody);
    const result = spawnSync('gh', ['pr', 'create', '--title', prTitle, '--body-file', bodyFile, '--base', baseBranch], {
      cwd,
      stdio: 'inherit',
    });
    fs.unlinkSync(bodyFile);
    if (result.status !== 0) throw new Error('gh pr create failed');
    console.log('\n✓ PR created successfully!');
  } catch {
    console.log('\n⚠️  Could not create PR automatically. Push completed - create PR manually.');
    console.log(`   Branch: ${branchName}`);
  }
}

function findHandlerDefinition(content: string, handlerName: string): number | null {
  const escaped = handlerName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const patterns = [
    new RegExp(`const\\s+${escaped}\\s*=`),
    new RegExp(`function\\s+${escaped}\\s*\\(`),
  ];

  const lines = content.split('\n');
  for (let i = 0; i < lines.length; i++) {
    for (const pattern of patterns) {
      if (pattern.test(lines[i])) {
        return i + 1; // 1-indexed
      }
    }
  }
  return null;
}

function getEffectiveTargetLine(content: string, gap: TrackingGap): number {
  const targetLine = gap.location?.line ?? 0;
  if (targetLine <= 0) return targetLine;

  const lines = content.split('\n');
  const lineIndex = targetLine - 1;

  // Build context: the line and nearby lines (onClick can span multiple lines)
  const contextStart = Math.max(0, lineIndex - 2);
  const contextEnd = Math.min(lines.length, lineIndex + 3);
  const context = lines.slice(contextStart, contextEnd).join('\n');

  // Check for direct handler: onClick={handleAddMapping} or inline: onClick={() => handlerName(...)}
  const directHandlerMatch = context.match(/onClick=\{(\w+)\}/);
  const inlineMatch = context.match(/onClick\s*=\s*\{[^}]*?(\w+)\s*\(/);
  const hint = gap.location?.hint ?? '';
  const hintMatch = hint.match(/onClick=\{[^}]*?(\w+)\s*\(/);

  const handlerName = directHandlerMatch?.[1] ?? inlineMatch?.[1] ?? hintMatch?.[1];
  if (handlerName) {
    const handlerLine = findHandlerDefinition(content, handlerName);
    if (handlerLine) {
      return handlerLine;
    }
  }

  return targetLine;
}

function generatePRBody(scanResult: ScanResult & { gaps?: TrackingGap[] }): string {
  const gaps = scanResult.gaps ?? [];
  const rows = gaps
    .map((g) => `| \`${g.suggestedEvent}\` | ${g.location?.file ?? 'TBD'} | ${g.priority} |`)
    .join('\n');

  return `## 📊 Analytics Events Added

This PR adds ${gaps.length} analytics tracking events to improve product observability.

### Events Added

| Event | Location | Priority |
|-------|----------|----------|
${rows}

### Product Context

**Mission:** ${scanResult.profile.mission}

**Key Metrics:** ${scanResult.profile.keyMetrics?.join(', ') ?? 'Not specified'}

---

*Generated by [Logline](https://github.com/yourname/logline)*`;
}

function insertTracking(content: string, targetLine: number, trackingCode: string): string {
  const lines = content.split('\n');
  let insertLine = targetLine > 0 ? targetLine - 1 : Math.floor(lines.length / 2);

  // Find a better insertion point - look for function handlers, useEffect
  if (targetLine > 0 && targetLine < lines.length) {
    for (let i = Math.max(0, targetLine - 20); i < Math.min(lines.length, targetLine + 20); i++) {
      const line = lines[i];
      if (/const\s+handle\w+\s*=|onClick\s*=|useEffect\s*\(/.test(line)) {
        for (let j = i; j < Math.min(lines.length, i + 10); j++) {
          if (lines[j].includes('{')) {
            insertLine = j + 1;
            break;
          }
        }
        break;
      }
    }

    if (insertLine === targetLine - 1) {
      for (let i = Math.max(0, targetLine - 10); i < targetLine; i++) {
        if (lines[i]?.includes('useState') && lines[i]?.includes('}')) {
          for (let j = i; j < Math.min(lines.length, i + 5); j++) {
            if (lines[j]?.trim() === ');') {
              insertLine = j + 1;
              break;
            }
          }
          break;
        }
      }
    }
  }

  insertLine = Math.max(0, Math.min(insertLine, lines.length - 1));
  const indent = lines[insertLine]?.match(/^(\s*)/)?.[1] ?? '  ';
  const indentedTrackingCode = trackingCode
    .trim()
    .split('\n')
    .map((l) => indent + l)
    .join('\n');

  const newLines = [...lines];
  newLines.splice(insertLine, 0, indentedTrackingCode);
  return newLines.join('\n');
}

function ensureTrackImport(content: string, filePath: string): string {
  const hasImport = /import\s+.*\btrack\b/.test(content) || content.includes("from '@/lib/analytics'") || content.includes("from '../lib/analytics'");
  if (hasImport) return content;

  const lines = content.split('\n');
  let lastImportIndex = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trim().startsWith('import ')) lastImportIndex = i;
  }

  const importPath = filePath.includes('src/') ? "import { track } from '@/lib/analytics';" : "import { track } from '../lib/analytics';";

  if (lastImportIndex >= 0) {
    lines.splice(lastImportIndex + 1, 0, importPath);
    return lines.join('\n');
  }

  // No imports - add at top
  lines.unshift(importPath, '');
  return lines.join('\n');
}

function ensureAnalyticsModule(cwd: string): void {
  const analyticsPath = path.join(cwd, 'src', 'lib', 'analytics.ts');

  if (fs.existsSync(analyticsPath)) return;

  const dir = path.dirname(analyticsPath);
  fs.mkdirSync(dir, { recursive: true });

  fs.writeFileSync(
    analyticsPath,
    `// Analytics module generated by Logline

export function track(eventName: string, properties: Record<string, unknown>): void {
  // TODO: Replace with your analytics provider
  // Examples:
  // - Segment: analytics.track(eventName, properties)
  // - PostHog: posthog.capture(eventName, properties)
  // - Mixpanel: mixpanel.track(eventName, properties)

  if (process.env.NODE_ENV === 'development') {
    console.log('[Analytics]', eventName, properties);
  }
}
`
  );

  console.log('  ✓ Created src/lib/analytics.ts');
}
